# -*- coding: utf-8 -*-
"""GitHub Data Extraction

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gXBnpC7BXgPFaR-SUljM_a_fCXiOx0jS
"""

pip install requests

import requests
import json

# GitHub credentials
GITHUB_USERNAME = "*********" # use your github username
GITHUB_TOKEN = "***********" # use your github personal token which can be generated

# GitHub API base URL
BASE_URL = "https://api.github.com"

# Headers for authentication
HEADERS = {
    "Authorization": f"token {GITHUB_TOKEN}",
    "Accept": "application/vnd.github.v3+json"
}

# Fetch all repositories
def get_repositories(username):
    url = f"{BASE_URL}/users/{username}/repos"
    response = requests.get(url, headers=HEADERS)

    if response.status_code == 200:
        return response.json()
    else:
        print("Error fetching repositories:", response.status_code)
        return []

# Fetch README content (full content, no limits)
def get_readme(repo_name):
    url = f"{BASE_URL}/repos/{GITHUB_USERNAME}/{repo_name}/readme"
    response = requests.get(url, headers=HEADERS)

    if response.status_code == 200:
        readme_data = response.json()
        readme_content = requests.get(readme_data["download_url"]).text
        return readme_content
    else:
        return "No README available"

# Fetch languages used in a repository
def get_languages(repo_name):
    url = f"{BASE_URL}/repos/{GITHUB_USERNAME}/{repo_name}/languages"
    response = requests.get(url, headers=HEADERS)

    if response.status_code == 200:
        return ", ".join(response.json().keys())
    else:
        return "Unknown"

# Main function to collect data and save it to a text file
def save_project_data():
    repos = get_repositories(GITHUB_USERNAME)
    file_path = "/content/github_projects.txt"  # File path in Google Colab

    with open(file_path, "w", encoding="utf-8") as file:
        for repo in repos:
            repo_name = repo["name"]
            description = repo["description"] or "No description provided"
            languages = get_languages(repo_name)
            readme_content = get_readme(repo_name)

            # Write to file
            file.write(f"📌 Repository: {repo_name}\n")
            file.write(f"📖 Description: {description}\n")
            file.write(f"💻 Technologies Used: {languages}\n")
            file.write("\n📜 README Content:\n")
            file.write(readme_content)
            file.write("\n" + "="*80 + "\n\n")  # Separator for readability

    print(f"✅ Data saved successfully in: {file_path}")

# Run the script
save_project_data()

# Display a download link for the file in Google Colab
from google.colab import files
files.download("/content/github_projects.txt")